os: Visual Studio 2015
configuration: Release

version: 0.9.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
- ps: >-
    nuget restore src\Cash.sln
- ps: >-
    ./scripts/SetReleaseVersion.ps1

# Do the build
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- ps: >-
    ./scripts/SetPackageVersion.ps1

build:
  project: src\Cash.sln
  parallel: false
  verbosity: minimal

branches:
  only:
    - master
    - develop

environment:
  EnableNuGetPackageRestore: true
  COVERALLS_REPO_TOKEN:
    secure: dKx1NBL7fa4s+psdSDbjUqGRNtRSTrcelFsU2jrddJas7ymlWmtX/vdBlQKmehLG

cache: packages -> **\packages.config


after_test: 
# generate report for MSTest testing framework:
- cmd: C:\projects\cash\src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:C:\projects\cash\src\Cash.Core.Tests\bin\Release\Cash.Core.Tests.dll /testcontainer:C:\projects\cash\src\Cash.Autofac.Tests\bin\Release\Cash.Autofac.Tests.dll /testcontainer:C:\projects\cash\src\Cash.Ninject.Tests\bin\Release\Cash.Ninject.Tests.dll" -output:coverage.xml
- cmd: C:\projects\cash\src\packages\coveralls.io.1.3.3\tools\coveralls.net.exe --opencover coverage.xml