version: 1.0.{build}
os: Visual Studio 2015
configuration: Release

init:
- cmd: PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build:
  project: src\Cash.Core\Cash.Core.sln
  parallel: false
  verbosity: detailed

environment:
  EnableNuGetPackageRestore: true
  COVERALLS_REPO_TOKEN:
    secure: dKx1NBL7fa4s+psdSDbjUqGRNtRSTrcelFsU2jrddJas7ymlWmtX/vdBlQKmehLG

cache: packages -> **\packages.config

before_build:
- cmd: nuget restore src\Cash.Core\Cash.Core.sln

after_test: 
# generate report for MSTest testing framework:
- cmd: C:\projects\cash\src\Cash.Core\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:C:\projects\cash\src\Cash.Core.Tests\bin\Release\Cash.Core.Tests.dll" -output:coverage.xml
- cmd: C:\projects\cash\src\Cash.Core\packages\coveralls.io.1.3.3\tools\coveralls.net.exe --opencover coverage.xml