pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include: [ "develop" ]
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet restore
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx --collect "Code coverage"
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1