pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include: [ "develop" ]
  
variables:
  buildConfiguration: 'Release'

# this translates into the $(Build.BuildNumber) variable.
name: $(Year:yy)$(DayOfYear).$(Rev:.r)

steps:
- script: |
    dotnet restore ./src/Cash.sln
    dotnet build ./src/Cash.sln --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: |
    dotnet pack ./src/Cash.sln --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1